### ISSUE TITLE
Mostrar status atuais no e-mail de novo pedido

### ISSUE THREAD

**Issue by leomp12** [ecomplus/transactional-mails#20]
Quando o pedido não estiver aguardando pagamento ou pagamento em análise, acho que é importante já informar o status da transação neste primeiro e-mail.

Para casos em que o pedido é aprovado instantaneamente por exemplo, ainda precisamos enviar o e-mail de novo pedido, mas o texto do e-mail informa:
_Seu pedido foi recebido e será processado após a aprovação do pagamento_

Em nenhum lugar ele cita que o pagamento já foi aprovado e dá a entender que está em aberto ainda, acho pouco informativo, o que você acha @vitorrgg ?

**Comment by vitorrgg** [comment]
Conferi que o `financial_status.current` é "paid", o texto deste primeiro e-mail é "Recebemos seu pagamento e estamos trabalhando para que você receba seu(s) produto(s) o mais rápido possível". Acredito que podemos fechar isso aqui.
