### ISSUE TITLE
[REFACTOR] mjml

### ISSUE THREAD

**Issue by leomp12** [ecomplus/transactional-mails#23]
Este [framework](https://github.com/mjmlio/mjml) parece bem bacana:
 - Já possui alguns [templates](https://mjml.io/templates) que aparentemente também são open source;
 - Tem algumas tags próprias com abstrações que ajudariam a manter o código mais limpo;
 - Melhor compatibilidade entre os clientes de e-mail, importante para templates mais complexos;

Já viu @vitorrgg ? Talvez pra uma próxima major disponilizando mais templates prontos.

> Não é um bug, nem prioridade, só acredito que facilitaria a implementação de novos templates no futuro (feature).

> Não subtitui o EJS, teríamos que compilar o template `mjml` primeiro para um HTML/EJS padrão, depois este template compilado seria renderizado com novamente com o EJS passando o data.

**Comment by vitorrgg** [comment]
Revivendo isso aqui @leomp12 , estou pensando em reconstruir esses templates para além de limpar o código, resolver os problemas de incompatibilidade com o outlook, que não descobri as causas. 

Mjml é o framework de e-mails usados no mailjet creio que podemos também após refazer esses e-mails, facilitar a customização através do app do mailjet, por já ter um exemplo de template mjml. Por onde começamos isso?

**Comment by leomp12** [comment]
@vitorrgg tem que dar uma refatorada no [`render`](https://github.com/ecomplus/transactional-mails/blob/master/src/lib/render.js) pra usar o `mjml` e então refatorar os templates. Você já pode começar com os templates e eu mexo no render depois se tiver dificuldade, mas aí você não conseguiria testar com `npm run serve` enquanto isto.

Isto deve ser feito em um novo branch `v2` (inclusive seria bom você removar alguns branchs seus parecem ociosos).

**Comment by leomp12** [comment]
@talissonf
