### ISSUE TITLE
Erro templates

### ISSUE THREAD

**Issue by talissonf** [ecomplus/transactional-mails#25]
@vitorrgg  Eu alterei a implementação do transactionalMails no SES, a implementação antiga silenciava as exceções quando aconteciam, talvez seja por isso que alguns status não estavam sendo notificados pelo SES.

Aqui no log de erros tem melhor descrição dos erros.

http://159.65.165.50/log/nodejs/ses.error

Acho que seria interessante testar novamente todo os status disponíveis para as orders pra ver se não aparece mais nenhum erro em outros templante.

**Comment by leomp12** [comment]
Acho que isto tá pendente ainda né @vitorrgg ?

**Comment by leomp12** [comment]
Teve um release aí mas tinha resolvido ainda não haha

**Comment by talissonf** [comment]
Ah foi mal, eu vi o release e atualizei o no ses :$

**Comment by leomp12** [comment]
Tá resolvido agora @vitorrgg ?

**Comment by talissonf** [comment]
Ainda ta rolando erro com esse template aqui; @vitorrgg @leomp12 
```bash
ecomplus-integrations [Thu Apr 23 2020 10:18:01 GMT-0300 (Brasilia Standard Time)] 
email_notification_err
{ TypeError: /var/nodejs/ses/node_modules/@ecomplus/transactional-mails/views/invoice_issued.ejs:59
    57|                                   <% order.shipping_lines.forEach(shipping => { %>
    58|                                       <td style="padding:10px 50px 10px 50px;line-height:22px;text-align:inherit;" height="100%" valign="top" bgcolor="">
 >> 59|                                       <% shipping.invoices.forEach(invoice => { %>
    60|                                           <div style="text-align: center;">
    61|                                             <font color="#333333">
    62|                                             <% if (invoice.link_danfe) { %>

Cannot read property 'forEach' of undefined
    at order.shipping_lines.forEach.shipping (/var/nodejs/ses/node_modules/@ecomplus/transactional-mails/views/invoice_issued.ejs:36:26)
    at Array.forEach (<anonymous>)
    at eval (/var/nodejs/ses/node_modules/@ecomplus/transactional-mails/views/invoice_issued.ejs:33:29)
    at invoice_issued (/var/nodejs/ses/node_modules/ejs/lib/ejs.js:682:17)
    at tryHandleCache (/var/nodejs/ses/node_modules/ejs/lib/ejs.js:254:36)
    at Object.exports.renderFile (/var/nodejs/ses/node_modules/ejs/lib/ejs.js:485:10)
    at Object.sass.render [as callback] (/var/nodejs/ses/node_modules/@ecomplus/transactional-mails/src/lib/render.js:85:15)
    at options.success (/var/nodejs/ses/node_modules/node-sass/lib/index.js:310:32)
  path:
   '/var/nodejs/ses/node_modules/@ecomplus/transactional-mails/views/invoice_issued.ejs' }
  ---  //  ---  
```

**Comment by vitorrgg** [comment]
Vou ver isso

**Comment by leomp12** [comment]
@talissonf não fui eu que fiz, mas pelo nome o template `invoice_issued` deveria ser acionado apenas se uma nota fiscal for emitida, certo? Você já está usando ele desta forma?
Neste caso `shipping.invoices` não deve ser undefiend...

**Comment by talissonf** [comment]
> @talissonf não fui eu que fiz, mas pelo nome o template `invoice_issued` deveria ser acionado apenas se uma nota fiscal for emitida, certo? Você já está usando ele desta forma?
> Neste caso `shipping.invoices` não deve ser undefiend...

Alguém pode ter alterado o status manualmente do pedido talvez, sem ter invoice.
