### ISSUE TITLE
Frase editável por e-mail

### ISSUE THREAD

**Issue by leomp12** [ecomplus/transactional-mails#28]
https://github.com/ecomplus/app-ses/issues/19

> @vitorrgg isto passa pelo `transactionalMails`, acho que ele não suportaria isto ainda, certo?
Todas as frases vêm do dicionário interno dele? Talvez se implementarmos um `mergeDictionary`...

**Comment by leomp12** [comment]
@talissonf pode fazer isto aqui pra nós depois por favor? E em seguida implementar no SES?

**Comment by talissonf** [comment]
Uai, posso.
